// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2024/10/23 下午11:00:22
const configMerger = require("/Users/billxu/project/Kyushu-maple-2024/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/billxu/project/Kyushu-maple-2024/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/billxu/project/Kyushu-maple-2024/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/billxu/project/Kyushu-maple-2024/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/billxu/project/Kyushu-maple-2024/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/billxu/project/Kyushu-maple-2024/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/billxu/project/Kyushu-maple-2024/src/plugins/**/*.{js,ts,mjs}","/Users/billxu/project/Kyushu-maple-2024/src/composables/**/*.{js,ts,mjs}","/Users/billxu/project/Kyushu-maple-2024/src/utils/**/*.{js,ts,mjs}","/Users/billxu/project/Kyushu-maple-2024/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/billxu/project/Kyushu-maple-2024/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/billxu/project/Kyushu-maple-2024/src/app.config.{js,ts,mjs}"] }));

module.exports = config
